services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: badat-api
    restart: unless-stopped
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: badat_football
      PGUSER: postgres
      PGPASSWORD: "${PGPASSWORD}"
      API_PORT: 3015
      SESSION_SECRET: ${SESSION_SECRET}
      WEB_ORIGIN: "http://shib.kefar-sava.co.il"
      VAPID_PUBLIC_KEY: "${VAPID_PUBLIC_KEY}"
      VAPID_PRIVATE_KEY: "${VAPID_PRIVATE_KEY}"
      VAPID_SUBJECT: "mailto:admin@shib.kefar-sava.co.il"
    ports:
      - "3116:3015"
    volumes:
      - api_uploads:/app/uploads
    networks:
      - postgres_default

  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
      args:
        VITE_API_URL: "https://shib.kefar-sava.co.il"
        VITE_VAPID_PUBLIC_KEY: "${VAPID_PUBLIC_KEY}"
    container_name: badat-client
    restart: unless-stopped
    ports:
      - "3082:80"

networks:
  postgres_default:
    external: true

volumes:
  api_uploads:
